// let uname = "Sachin";  // String
// document.write("My name is ", uname, "<br>")

// let age = 20;       // Number
// document.write("My age is ", age)

// ------------------------------

// let isStudent = true; // Boolean
// document.write(isStudent?"Yes":"No")

// let emptyValue = "mobile"; // Null
// document.write(emptyValue?"not fille": "filled")
// document.write( emptyValue && "filled")

// ------------------

let uninitialized; // Undefined
document.write(uninitialized || "You have not passed")
